// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBehuOz3BG42fgTICOD3D6MFzr-zogJSFE',
    appId: '1:819612318841:web:b2d44b4ed399c4b6c068a8',
    messagingSenderId: '819612318841',
    projectId: 'course-hotelio-3d9a0',
    authDomain: 'course-hotelio-3d9a0.firebaseapp.com',
    storageBucket: 'course-hotelio-3d9a0.appspot.com',
    measurementId: 'G-MWC5FGPSBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrmcNCqgkI2SKxalb-92GATzMCdn_Cno',
    appId: '1:819612318841:android:52918a8097dea8c9c068a8',
    messagingSenderId: '819612318841',
    projectId: 'course-hotelio-3d9a0',
    storageBucket: 'course-hotelio-3d9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_11xq83r2uQQRv3xv27oAvN2Q1x6JcHA',
    appId: '1:819612318841:ios:e5965aa1b1f3d68dc068a8',
    messagingSenderId: '819612318841',
    projectId: 'course-hotelio-3d9a0',
    storageBucket: 'course-hotelio-3d9a0.appspot.com',
    iosClientId: '819612318841-gnissvhs8ihif7e0r7vd9suqjqlh5c3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio.courseHotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_11xq83r2uQQRv3xv27oAvN2Q1x6JcHA',
    appId: '1:819612318841:ios:87de4e4bfa58394ac068a8',
    messagingSenderId: '819612318841',
    projectId: 'course-hotelio-3d9a0',
    storageBucket: 'course-hotelio-3d9a0.appspot.com',
    iosClientId: '819612318841-8b9e7oit15gkfetqlmnm1ahubucae5fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio.courseHotelio.RunnerTests',
  );
}
